OdeToFood/OdeToFood/Models/CuisineType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.Models
{
    public enum CuisineType
    {
        None,
        Italian,
        French,
        Greek
    }
}

OdeToFood/OdeToFood/Models/Restaurant.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations;

namespace OdeToFood.Models
{
    public class Restaurant
    {
        public int Id { get; set; }
        [Display(Name="Restaurant Name")]
        [Required, MaxLength(80)]
        public string Name { get; set; }
        public CuisineType Cuisine { get; set; }
    }
}

OdeToFood/OdeToFood/ViewModels/HomeIndexViewModel.cs
using OdeToFood.Models;
using System.Collections.Generic;

namespace OdeToFood.ViewModels
{
    public class HomeIndexViewModel
    {
        public IEnumerable<Restaurant> Restaurants { get; set; }
        public string CurrentMessage { get; set; }
    }
}

OdeToFood/OdeToFood/ViewModels/RestaurantEditModel.cs
using OdeToFood.Models;
using System.ComponentModel.DataAnnotations;

namespace OdeToFood.ViewModels
{
    public class RestaurantEditModel
    {
        [Required,MaxLength(80)]
        public string Name { get; set; }
        public CuisineType Cuisine { get; set; }
    }
}

OdeToFood/OdeToFood/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace OdeToFood.Controllers
{
    [Route("company/[controller]/[action]")]
    public class AboutController
    {
        //[Route("")]
        public string Phone()
        {
            return "+0030 6944313322";
        }
        //[Route("[action]")]
        public string Address()
        {
            return "Greece";
        }
    }
}

OdeToFood/OdeToFood/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Models;
using OdeToFood.Services;
using OdeToFood.ViewModels;

namespace OdeToFood.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private IRestaurantData _restaurantData;
        private IGreeter _greeter;

        public HomeController(IRestaurantData restaurantData, IGreeter greeter
            )
        {
            _restaurantData = restaurantData;
            _greeter = greeter;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            var rest = new HomeIndexViewModel();
            rest.Restaurants = _restaurantData.GetAll();
            rest.CurrentMessage = _greeter.GetMessageOfTheDay();
            // return new ObjectResult(rest);
            // return Content("Hello from home !!!");
            return View(rest);
        }

        public IActionResult Details(int id)
        {
            var model = _restaurantData.Get(id);

            if (model == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RestaurantEditModel restaurant)
        {
            if (ModelState.IsValid)
            {
                var newRestaurant = new Restaurant();

                newRestaurant.Name = restaurant.Name;
                newRestaurant.Cuisine = restaurant.Cuisine;

                newRestaurant = _restaurantData.Add(newRestaurant);

                return RedirectToAction(nameof(Details), new { Id = newRestaurant.Id });
            }
            else
            {
                return View();
            }
        }
    }
}

OdeToFood/OdeToFood/Pages/Greeting.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Services;

namespace OdeToFood.Pages
{
    public class GreetingModel : PageModel
    {
        private IGreeter _greeder;

        public string CurrentGreeting { get; set; }

        public GreetingModel(IGreeter greeder)
        {
            _greeder = greeder;
        }
        public void OnGet(string name)
        {
            CurrentGreeting = $"{name} : {_greeder.GetMessageOfTheDay()}";
        }
    }
}

OdeToFood/OdeToFood/Pages/Restaurants/Edit.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Models;
using OdeToFood.Services;

namespace OdeToFood.Pages.Restaurants
{
    [Authorize]
    public class EditModel : PageModel
    {
        private IRestaurantData _restaurantData;

        [BindProperty]
        public Restaurant Restaurant { get; set; }

        public EditModel(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }
        public IActionResult OnGet(int Id)
        {
           Restaurant = _restaurantData.Get(Id);
            if (Restaurant==null)
            {
                return RedirectToAction("Index", "Home");
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                _restaurantData.Update(Restaurant);

                return RedirectToAction("Details", "Home", new { Id = Restaurant.Id });
            }
            return Page();
        }
    }
}

OdeToFood/OdeToFood/ViewsComponents/GreeterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewsComponents
{
    public class GreeterViewComponent : ViewComponent
    {
        private IGreeter _greeter;

        public GreeterViewComponent(IGreeter greeter)
        {
            _greeter = greeter;
        }

        public IViewComponentResult Invoke()
        {
            var model = _greeter.GetMessageOfTheDay();

            return View("Default", model);
        }
    }
}

OdeToFood/OdeToFood/Pages/Greeting.cshtml
@page "{name}"

@inject IGreeter Greeter;

@model GreetingModel

<div>Hello !!! @Greeter.GetMessageOfTheDay()</div>

<div> @Model.CurrentGreeting from model</div>

OdeToFood/OdeToFood/Pages/Restaurants/Edit.cshtml
@page "{id}"
@using OdeToFood.Pages.Restaurants

@model EditModel

<h1>Edit @Model.Restaurant.Name</h1>
<form method="post">
    <input type="hidden" asp-for="Restaurant.Id"/>
    <div>
        <label asp-for="Restaurant.Name"></label>
        <input asp-for="Restaurant.Name" />
        <span asp-validation-for="Restaurant.Name" style="color:red"></span>
    </div>

    <label asp-for="Restaurant.Cuisine"></label>
    <select asp-for="Restaurant.Cuisine" asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
    <span asp-validation-for="Restaurant.Cuisine"></span>
    <input type="submit" name="Save" value="Save" />
</form>

OdeToFood/OdeToFood/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>
        @RenderSection("footer",required:false)
    </footer>
</body>
</html>

OdeToFood/OdeToFood/Views/Home/Create.cshtml
@using OdeToFood.Models;
@model Restaurant

@{ 
    ViewBag.Title = "Create";
}

<h1>Create</h1>
<form method="post">

    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name" style="color:red"></span>
    </div>

    <label asp-for="Cuisine"></label>
    <select asp-for="Cuisine" asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
    <span asp-validation-for="Cuisine"></span>
    <input type="submit" name="Save" value="Save" />
</form>

OdeToFood/OdeToFood/Views/Home/Details.cshtml
@*@model OdeToFood.Models.Restaurant*@
@model Restaurant
@{
    ViewBag.Title = "Details";
}

<h1>@Model.Name</h1>
<div>Id: @Model.Id</div>
<div>Cuisine Type: @Model.Cuisine</div>
<a asp-action="Index" asp-controller="Home">Home</a>

OdeToFood/OdeToFood/Views/Home/Index.cshtml
@model OdeToFood.ViewModels.HomeIndexViewModel

@{
    ViewBag.Title = "Home Page";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>All Restaurants</h1>

@foreach (var restaurant in Model.Restaurants)
{
    @await Html.PartialAsync("_Summary", restaurant);
}

    @*<table>
        @foreach (var restaurant in Model.Restaurants)
        {
            <tr>
                <td>@restaurant.Id</td>
                <td>@restaurant.Name</td>
                <td>
                    @*<a href="/home/details/@restaurant.Id">details...</a>
                        @Html.ActionLink("Go", "Details", new { id = restaurant.Id });
                    <a asp-action="Details" asp-route-id="@restaurant.Id">More</a>
                    <a asp-page="/Restaurants/Edit" asp-route-id="@restaurant.Id">Edit</a>
                </td>
            </tr>
        }

    </table>
*@

                    <div><a class="btn btn-primary" asp-action="Create">Add restaurant</a></div>
@*<h1>@Model.Name</h1>*@
@*<div>The id value is @Model.Id</div>*@

@*@section footer {
    @Model.CurrentMessage
}*@

OdeToFood/OdeToFood/Views/Home/_Summary.cshtml
@model Restaurant

<section class="panel panel-default">
    <h3 class="panel-heading">@Model.Name</h3>
    <div class="panel-body">
        Cuisine: @Model.Cuisine
    </div>
    <div class="panel-footer">
        <a class="btn btn-default" asp-action="Details" asp-route-id="@Model.Id">More</a>
        <a class="btn btn-default" asp-page="/Restaurants/Edit" asp-route-id="@Model.Id">Edit</a>
    </div>
 </section>

OdeToFood/OdeToFood/Views/Shared/Components/Greeter/Default.cshtml
@model string

<div>
    @Model
</div>

OdeToFood/OdeToFood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid"></div>
        <div class="navbar-header">
            <a class="navbar-brand" href="/">OdeToFood</a>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
        <footer>
            @RenderSection("footer", required: false)
            @*@await Component.InvokeAsync("Greeter")*@
            <vc:greeter></vc:greeter>
            @*@if (User.Identity.IsAuthenticated)
                {
                    foreach(var idenity in User.Identities)
                    {
                        <h3>@idenity.Name</h3>
                         <ul>
                            @foreach(var claim in idenity.Claims)
                            {
                                <li>@claim.Type - @claim.Value</li>
                            }
                        </ul>
                    }
                }
                else
                {
                       <div>You are anonymous</div>
                }*@
        </footer>
    </div>
    <environment include="Development">
        <script src="~/node_modules/jquery/dist/jquery.js"></script>
        <script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
    </environment>

</body>
</html>